# Explicitly select the default infrastructure
sudo: required
language: python

python:
  - "2.7"

services:
  - docker

branches:
  only:
  - btelnes

# command to install dependencies
# Note: Keep this to avoid "Could not locate requirements.txt.  Override the install: key in your .travis.yml to install dependencies"
install:

before_install:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker pull btelnes/devstack
  - docker run -d --name devstack --add-host "localhost preview.localhost":127.0.0.1 --security-opt seccomp=unconfined --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro -t btelnes/devstack
  - docker ps -a

# command to run tests
script: ./scripts/travis-test.sh

dist: trusty
