language: python
python:
  - "2.7"

services:
  - docker

branches:
  only:
  # - master
  # - oxa/master.fic
  # - oxa/devfic
  # Testing CI Branch
  - oxa/ci
  - btelnes

# command to run tests
script: ./scripts/travis-tests.sh

dist: trusty
