# Explicitly select the default infrastructure
sudo: required
language: python

python:
  - "2.7"

services:
  - docker

branches:
  only:
  - btelnes

before_install:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker pull btelnes/devstack
  - docker run -d --name devstack --security-opt seccomp=unconfined --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro -t btelnes/devstack
  - docker ps -a

# command to install dependencies
install:
  # Fix an issue caused by /var/lib/mongodb/mongod.lock (Exception in initAndListen: 12596 old lock file)
  - sudo -u mongodb mongod --repair --dbpath /var/lib/mongodb/
  - sudo service mongod start

# command to run tests
script: ./scripts/travis-test.sh

dist: trusty
